version: '3.8'

services:
  # Database
#  postgres:
#    image: postgres:15
#    container_name: postgres
#    environment:
#      POSTGRES_DB: silvercart
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - app-net

  # Redis Cache
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-net

  # Redis Insight - GUI Management Tool
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    networks:
      - app-net

 
  # API Service
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silvercart-webapi
    depends_on:
      - postgres
      - kafka
      - redis
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseConnection=Host=postgres;Database=silvercart;Username=postgres;Password=postgres
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__GroupId=silvercart-order-group
      - Kafka__OrdersTopic=orders
      - Redis__ConnectionString=redis:6379
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  redis_insight_data: 